### PR TITLE
password strength meter

### PR DESCRIPTION
**Pull request by shahroq**
adding password strength meter to `PasswordInput.vue` component:

### CODE REVIEW

**Comment by KorvinSzanto** [comment]
This looks like a valuable addition to me, two things I'd request:
1. Update this to match our code style guidelines, check out the "Vue" section [here](https://documentation.concretecms.org/tutorials/submitting-code-to-concrete5) (I only see scope indentation not matching)
2. Update the "Strong" category to recommend 16 character minimum to match what [security.org recommends](https://www.security.org/how-secure-is-my-password/)

**Comment by shahroq** [comment]
1. Re the style indentation as I see the other Vue files follow the same 2-space indentation. I ran `lint:fix` again and the result was the same. Am I missing something here?

2. About password security, I thought 16 characters is too much to ask for ordinary users. What about 12 on `Strong`? Another option would be appending another level labeled `Very Strong` for 16-character+ passwords.

**Comment by aembler** [comment]
I think I'd go with adding a Very Strong label for 16+ characters. Or honestly whatever the browser best practice is: eg if Safari or Chrome suggests a password with characters and of a certain length that should probably be labeled as very strong by our algorithm. 

Additionally can you localize this? We have the ccmi18n array driven by the assets_localization controller in the core - all strings in these components should use keys in those JS arrays instead of hard-coding English

**Comment by shahroq** [comment]
@aembler done.

**Comment by aembler** [comment]
This has been merged into the 1.4.x branch (for use in 9.2.0)

**Pull request closed without merging**
