### PR TITLE
Add group selector

### PR DESCRIPTION
**Pull request by mlocati**
Companion of https://github.com/concretecms/concretecms/pull/10966

### CODE REVIEW

**Comment by mlocati** [comment]
> can you reopen it against the 1.4.x branch?

I've just updated this PR, rebasing it against the 1.4.x branch



> can you fix the code linting errors?

Done.

**Comment by mlocati** [comment]
>>  can you fix the code linting errors?

> Done.

BTW I don't understand why the lint process doesn't accept the null safe operator (`?.`): it gets transpiled correctly to some code compatible with old browsers when building the final assets...

**Comment by aembler** [comment]
@mlocati Yeah you'll probably have to ask @KorvinSzanto about that one - that's above my understanding of JS 😅

**Comment by mlocati** [comment]
Here's a pull request that fixes the lint issue: #257

**Pull request merged**
